from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    """Post _summary_
    a Django model maps to a single table in the database
    in which each field of the model represents a column in the table
    """

    # Django sees a field in the model with the primary_key=True,
    # it won’t add the automatic id column.
    post_id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=120)
    content = models.TextField()
    published_at = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    # class Meta:
    #     """to specify a table name
    #     instead of using the default name generated by Django
    #     """

    #     # db_table = "posts"

    #     ordering = ["-published_at"]
